### ISSUE TITLE
Add Weapon Abstract Class

### ISSUE THREAD

**Issue by JasonLConcordiaSTP** [JasonLConcordiaSTP/ZombieWar#22]

**Comment by wkndevguy** [comment]
Created Weapon abstract class with two instance variables `damage` and `accuracy`, both `int`. Created default constructor, parameterized constructor, as well as getters and setters for the two properties.

**NOTE**: `int` was used for the accuracy property. Using a value from 1-100 will allow the main method of the game class to use that to calculate the probability that an attack will hit, or miss depending on the implementation.
