### ISSUE TITLE
ICharacter Interface

### ISSUE THREAD

**Issue by JasonLConcordiaSTP** [JasonLConcordiaSTP/ZombieWar#7]
Add ICharacter

**Comment by wkndevguy** [comment]
@JasonLConcordiaSTP the method names may be confusing. Please let me know if I'm correct in my thinking here:
- calculateAttackDamage() this gets the amount of damage done to an enemy by this character's attack
- damage(int) Should this be renamed attack(int) ? This is the attack move dealing this player's damage to the enemy
- getHealthPoints() Should this be simplified to getHeath() ? HealthPoints could be abbreviated to HP which could easily be confused with Hit Points.
- getName() got it :)

**Comment by wkndevguy** [comment]
Met with Jason (WebEx). Changed methods to reflect current design. New methods are:
- int getHealth()  <--**edit:** added missing paren's
- setHealth(int i)
- int getAttackDamage()
- String getName()

**Comment by wkndevguy** [comment]
Closing
